CREATE TABLE actors
(
    actor_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                             NOT NULL,
    age      INTEGER,
    CONSTRAINT pk_actors PRIMARY KEY (actor_id)
);

CREATE TABLE countries
(
    country_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    CONSTRAINT pk_countries PRIMARY KEY (country_id)
);

CREATE TABLE films
(
    film_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(256)                             NOT NULL,
    duration_minutes INTEGER,
    year             SMALLINT,
    cash_success     INTEGER,
    date_creation    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_films PRIMARY KEY (film_id)
);

CREATE TABLE films_actors
(
    actor_id INTEGER NOT NULL,
    film_id  INTEGER NOT NULL
);

CREATE TABLE films_countries
(
    country_id INTEGER NOT NULL,
    film_id    INTEGER NOT NULL
);

ALTER TABLE actors
    ADD CONSTRAINT uc_actors_actor UNIQUE (actor_id);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_country UNIQUE (country_id);

ALTER TABLE films_actors
    ADD CONSTRAINT uc_films_actors_film UNIQUE (film_id);

ALTER TABLE films_countries
    ADD CONSTRAINT uc_films_countries_film UNIQUE (film_id);

ALTER TABLE films
    ADD CONSTRAINT uc_films_film UNIQUE (film_id);

ALTER TABLE films_actors
    ADD CONSTRAINT fk_filact_on_actor FOREIGN KEY (actor_id) REFERENCES actors (actor_id);

ALTER TABLE films_actors
    ADD CONSTRAINT fk_filact_on_film FOREIGN KEY (film_id) REFERENCES films (film_id);

ALTER TABLE films_countries
    ADD CONSTRAINT fk_filcou_on_country FOREIGN KEY (country_id) REFERENCES countries (country_id);

ALTER TABLE films_countries
    ADD CONSTRAINT fk_filcou_on_film FOREIGN KEY (film_id) REFERENCES films (film_id);